// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCK63nMDFqYxqczxeGYZTzMezYBm1d7Bf8',
    appId: '1:218371911788:web:cfb5876656e53abd412849',
    messagingSenderId: '218371911788',
    projectId: 'revisai-c7659',
    authDomain: 'revisai-c7659.firebaseapp.com',
    storageBucket: 'revisai-c7659.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWQFPliYgLAzHBdtyWZOWB6UcBQB4LAtE',
    appId: '1:218371911788:android:f9a88e41796939e5412849',
    messagingSenderId: '218371911788',
    projectId: 'revisai-c7659',
    storageBucket: 'revisai-c7659.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiUCw1UoE-Io8Sk6A5_QoaZRQoPcwBAVs',
    appId: '1:218371911788:ios:38a832c0dc4f680a412849',
    messagingSenderId: '218371911788',
    projectId: 'revisai-c7659',
    storageBucket: 'revisai-c7659.firebasestorage.app',
    iosBundleId: 'com.example.revisai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiUCw1UoE-Io8Sk6A5_QoaZRQoPcwBAVs',
    appId: '1:218371911788:ios:38a832c0dc4f680a412849',
    messagingSenderId: '218371911788',
    projectId: 'revisai-c7659',
    storageBucket: 'revisai-c7659.firebasestorage.app',
    iosBundleId: 'com.example.revisai',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCK63nMDFqYxqczxeGYZTzMezYBm1d7Bf8',
    appId: '1:218371911788:web:85040e48c86151f1412849',
    messagingSenderId: '218371911788',
    projectId: 'revisai-c7659',
    authDomain: 'revisai-c7659.firebaseapp.com',
    storageBucket: 'revisai-c7659.firebasestorage.app',
  );
}
